# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  desc "Push a new artifact build internal"
  lane :internal do |options|
      buildNumber = latest_testflight_build_number
      incrementBuildNumber(buildNumber)
      increment_version_number( bump_type: options[:versionType] )
      build_ios_app(
        scheme: "Release"
      )
      upload_to_testflight
      # sendMessageSlack()

  end

  def incrementBuildNumber(val)
    if val != nil
      increment_build_number({
     build_number: val + 1
    })
    end
  end
  
  def incerementVersionNumber(versionType)
    if versionType != nil
      increment_version_number( bump_type: options[:versionType] )
    end
  end

end